### ISSUE TITLE
Search field

### ISSUE THREAD

**Issue by ccd0** [MayhemYDG/archives.json#21]
Desustorage won't be supporting search for any boards except /mlp/ and /qa/ until new servers are purchased:
https://desustorage.org/desu/thread/72/#136

It would be useful to have a list of what archives supported search on what boards, similar to the list of which boards an archive has full images for.  For convenience, you could take the convention that all boards are searchable unless a "search" entry is present to say otherwise.

**Comment by MayhemYDG** [comment]
Done in:
a37d26c4a6244de44c22024c62be395ac20cc9f7
593e3d8d50de63e4946e8c79ead0ec3bea125ff1
