### ISSUE TITLE
GitHub Pages Backup URL

### ISSUE THREAD

**Issue by r3c0d3x** [MayhemYDG/archives.json#31]
Seeing as how Github Pages supports CORS [[0]](https://twitter.com/annevk/status/574261459712143361)[[1]](https://i.imgur.com/PmtcrqI.png), we could rename our `master` branch to `gh-pages` in order to have GitHub Pages serve as a mirror for our current URL [[2]](https://4chan-x.just-believe.in/json/archives.json). The only difference would between the two would be that our current URL serves a minified version of the JSON, while the potential future URL [[3]](https://mayhemydg.github.io/archives.json/archives.json) would return the JSON as-is. Both serve files over HTTPS and update their content based on the repo fairly quickly.

**Comment by MayhemYDG** [comment]
Done!
