### ISSUE TITLE
On the Allocation of Archive IDs

### ISSUE THREAD

**Issue by r3c0d3x** [MayhemYDG/archives.json#35]
Should we have a list of all of the allocated archive IDs (or at very least the newest archive ID to use if adding to the list)? This will make the lives of future archive maintainers much easier, and has been an issue (bad pun) in the past: 
https://github.com/MayhemYDG/archives.json/pull/1#discussion_r18681710, https://github.com/MayhemYDG/archives.json/pull/24/commits/bd035f582c5d2b13610fa30d5f2d257fa23b310e, https://github.com/MayhemYDG/archives.json/pull/29#issuecomment-204734981, etc.

Here's the plan if you agree to the list idea:
- We come up with how we want to do it (JSON for programmatic access or just a nice markdown file, I recommend the latter), and implement a template for it (for just one sample archive).
- I (or someone else, if anybody wants to) go through the git commit history and add them to the list and just make a PR referencing this issue when I finish.
- Update the list whenever a new archive is added.

And/or if we want to have the newest archive ID to use then we can just include that somewhere in the [CONTRIBUTING.md](https://github.com/MayhemYDG/archives.json/blob/gh-pages/CONTRIBUTING.md).

**Comment by MayhemYDG** [comment]
A markdown file is better. If you want to do it go for it.

**Comment by bstats** [comment]
here's a list of the allocations in CSV format: (uid,name,url)
```
0,Foolz,archive.foolz.us
1,NSFW Foolz,nsfw.foolz.us
2,The Dark Cave,archive.thedarkcave.org
3,4plebs,archive.4plebs.org
4,Nyafuu,archive.nyafuu.org
5,Love is Over,loveisover.me
6,nth-chan,nth.pensivenonsen.se
7,Install Gentoo,archive.installgentoo.net
8,Rebecca Black Tech,archive.rebeccablacktech.com
9,Heinessen,archive.heinessen.com
10,warosu,fuuka.warosu.org
11,Foolz a Shit,archive.foolzashit.com
12,FapArchive,fuuka.worldathleticproject.org
13,Foolz Beta,beta.foolz.us
14,Bui's Archive,archive.bui.pm
15,Fgts,fgts.jp
16,maware,archive.mawa.re
17,installgentoo.com,chan.installgentoo.com
18,Innovandalism Archive,boards.innovandalism.eu
19,Deniable Plausibility,boards.deniableplausibility.net
20,/v/idya archive,archive.vidya.moe
21,imcute,imcute.yt
22,not4plebs,totally.not4plebs.org
23,DesuStorage,archive.desustorage.org
24,fireden.net,boards.fireden.net
25,arch.b4k.co,arch.b4k.co
26,poweredby.moe,archive.poweredby.moe
27,4ch.be,4ch.be
28,bstats,archive.b-stats.org
```

**Comment by r3c0d3x** [comment]
Sweet, thanks! Was planning on getting this done sometime after finals (this upcoming week).
